use crate::config::NaviConfig;
use crate::scanner::scan_routes;
use anyhow::Result;
use std::collections::HashMap;

pub fn generate_route_tree(config: &NaviConfig) -> Result<String> {
    let routes = scan_routes(config)?;

    let mut use_statements = String::new();
    let mut route_definitions = String::new();
    let mut add_route_calls = String::new();
    let mut used_aliases: HashMap<String, String> = HashMap::new();

    for route in &routes {
        let module_path = &route.module_name;
        let pascal_name = &route.pascal_name;
        let route_pattern = &route.route_pattern;

        let alias = if used_aliases.contains_key(module_path) {
            format!("{}_route", pascal_name)
        } else {
            pascal_name.clone()
        };
        used_aliases.insert(module_path.clone(), alias.clone());

        use_statements.push_str(&format!(
            "use crate::routes::{} as {};\n",
            module_path, alias
        ));

        route_definitions.push_str(&format!(
            "define_route!({}, path: \"{}\");\n",
            alias, route_pattern
        ));

        add_route_calls.push_str(&format!("    tree.add_route({}::build_node());\n", alias));
    }

    let output = format!(
        r#"// AUTO-GENERATED by navi-codegen - DO NOT EDIT
#[allow(unused_imports)]
use navi_macros::define_route;

{use_statements}

{route_definitions}

/// Build the route tree with all discovered routes.
pub fn build_route_tree() -> navi_router::RouteTree {{
    let mut tree = navi_router::RouteTree::new();
{add_route_calls}
    tree
}}
"#,
        use_statements = use_statements,
        route_definitions = route_definitions,
        add_route_calls = add_route_calls,
    );

    Ok(output)
}

pub fn write_route_tree(config: &NaviConfig) -> Result<()> {
    let content = generate_route_tree(config)?;
    std::fs::write(&config.generated_route_tree, content)?;
    Ok(())
}
