// navi-codegen/src/generator.rs
use crate::config::NaviConfig;
use crate::scanner::scan_routes;
use anyhow::Result;
use std::collections::HashMap;
use std::path::Path;

pub fn generate_route_tree(config: &NaviConfig) -> Result<String> {
    let routes = scan_routes(config)?;

    let mut modules = String::new();
    let mut route_nodes = String::new();

    // Group routes by module path to avoid duplicates
    let mut seen_modules: HashMap<String, String> = HashMap::new();

    for route in &routes {
        let module_path = &route.module_name;
        let _route_id = &route.route_id;
        let pascal_name = &route.pascal_name;

        // Generate a stub params struct if the route has dynamic segments
        let params_struct = if route.has_dynamic_segment {
            format!(
                r#"
            #[derive(Clone, Debug, Default, serde::Deserialize)]
            pub struct Params {{}}
            "#
            )
        } else {
            String::new()
        };

        let module_content = if !seen_modules.contains_key(module_path) {
            seen_modules.insert(module_path.clone(), pascal_name.clone());
            format!(
                r#"
pub mod {mod_name} {{
    use navi_macros::define_route;
    {params_struct}

    define_route!(
        {pascal_name}Route,
        path: "{pattern}",
        params: Params,
        is_layout: {is_layout},
        is_index: {is_index},
    );
}}
"#,
                mod_name = module_path.split("::").last().unwrap(),
                pascal_name = pascal_name,
                pattern = route.route_pattern,
                is_layout = route.is_layout,
                is_index = route.is_index,
                params_struct = params_struct,
            )
        } else {
            String::new()
        };

        modules.push_str(&module_content);

        let parent_field = if let Some(ref parent) = route.parent {
            format!("Some(\"{}\".into())", parent)
        } else {
            "None".into()
        };

        route_nodes.push_str(&format!(
            r#"
    {{
        let mut node = routes::{module}::{pascal}Route::build_node();
        node.parent = {parent};
        tree.add_route(node);
    }}
"#,
            module = module_path,
            pascal = pascal_name,
            parent = parent_field,
        ));
    }

    let output = format!(
        r#"// AUTO-GENERATED by navi-codegen - DO NOT EDIT
#[allow(unused_imports)]
use navi_router::RouteTree;

pub mod routes {{
    {modules}
}}

/// Build the route tree with all discovered routes.
pub fn build_route_tree() -> RouteTree {{
    let mut tree = RouteTree::new();
    {route_nodes}
    tree
}}
"#,
        modules = modules,
        route_nodes = route_nodes,
    );

    Ok(output)
}

pub fn write_route_tree(config: &NaviConfig) -> Result<()> {
    let content = generate_route_tree(config)?;
    let out_path = Path::new(&config.generated_route_tree);
    if let Some(parent) = out_path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(out_path, content)?;
    Ok(())
}
