use crate::config::NaviConfig;
use crate::scanner::{RouteInfo, scan_routes};
use anyhow::Result;

/// Generate the route tree Rust module from scanned routes.
pub fn generate_route_tree(config: &NaviConfig) -> Result<String> {
    let routes = scan_routes(config)?;

    let mut use_statements = String::new();
    let mut route_definitions = String::new();
    let mut add_route_calls = String::new();

    for route in &routes {
        let module_name = &route.module_name;
        let route_pattern = &route.route_pattern;

        use_statements.push_str(&format!(
            "use crate::routes::{};\n",
            module_name
        ));

        route_definitions.push_str(&format!(
            "define_route!({}, path: \"{}\");\n",
            to_pascal_case(module_name),
            route_pattern
        ));

        add_route_calls.push_str(&format!(
            "tree.add_route({}::build_node());\n",
            to_pascal_case(module_name)
        ));
    }

    let output = format!(
        r#"// AUTO-GENERATED by navi-codegen - DO NOT EDIT
#![allow(unused)]

{use_statements}

{route_definitions}

/// Build the route tree with all discovered routes.
pub fn build_route_tree() -> navi_router::RouteTree {{
    let mut tree = navi_router::RouteTree::new();
    {add_route_calls}
    tree
}}
"#,
        use_statements = use_statements,
        route_definitions = route_definitions,
        add_route_calls = add_route_calls,
    );

    Ok(output)
}

/// Convert a snake_case or kebab-case name to PascalCase.
fn to_pascal_case(name: &str) -> String {
    name.split('_')
        .flat_map(|s| s.split('-'))
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                None => String::new(),
                Some(first) => {
                    let upper: String = first.to_uppercase().collect();
                    format!("{}{}", upper, chars.as_str())
                }
            }
        })
        .collect()
}

/// Write the generated route tree to a file.
pub fn write_route_tree(config: &NaviConfig) -> Result<()> {
    let content = generate_route_tree(config)?;
    std::fs::write(&config.generated_route_tree, content)?;
    Ok(())
}
