// AUTO-GENERATED by navi-codegen - DO NOT EDIT

// Module declarations for discovered routes
#[path = "routes/(marketing)/about.rs"] pub mod _marketing__about;
#[path = "routes/__root.rs"] pub mod __root;
#[path = "routes/_auth/mod.rs"] pub mod _auth;
#[path = "routes/_auth/profile.rs"] pub mod _auth_profile;
#[path = "routes/about.rs"] pub mod about;
#[path = "routes/admin/dashboard.rs"] pub mod admin_dashboard;
#[path = "routes/admin/mod.rs"] pub mod admin;
#[path = "routes/awaited.rs"] pub mod awaited;
#[path = "routes/blocking.rs"] pub mod blocking;
#[path = "routes/dashboard/analytics.rs"] pub mod dashboard_analytics;
#[path = "routes/dashboard/index.rs"] pub mod dashboard_index;
#[path = "routes/dashboard/mod.rs"] pub mod dashboard;
#[path = "routes/dashboard/settings.rs"] pub mod dashboard_settings;
#[path = "routes/docs/$.rs"] pub mod docs_splat;
#[path = "routes/index.rs"] pub mod index;
#[path = "routes/lifecycle.rs"] pub mod lifecycle;
#[path = "routes/login.rs"] pub mod login;
#[path = "routes/scroll.rs"] pub mod scroll;
#[path = "routes/settings.rs"] pub mod settings;
#[path = "routes/users/$id.rs"] pub mod users_param_id;
#[path = "routes/users/index.rs"] pub mod users_index;
#[path = "routes/users/{-}.rs"] pub mod users____;
#[path = "routes/validation-test/garde.rs"] pub mod validation_test_garde;
#[path = "routes/validation-test/index.rs"] pub mod validation_test_index;
#[path = "routes/validation-test/valico.rs"] pub mod validation_test_valico;
#[path = "routes/validation-test/validator.rs"] pub mod validation_test_validator;
#[path = "routes/validation-test/validify.rs"] pub mod validation_test_validify;

/// Build the route tree with all discovered routes.
pub fn build_route_tree() -> navi_router::RouteTree {
    let mut tree = navi_router::RouteTree::new();

    {
        let mut node = about::AboutRoute::build_node();
        node.parent = Some("RootRoute".into());
        tree.add_route(node);
    }

    {
        let mut node = __root::RootRoute::build_node();
        node.parent = None;
        tree.add_route(node);
    }

    {
        let mut node = scroll::ScrollRoute::build_node();
        node.parent = Some("RootRoute".into());
        tree.add_route(node);
    }

    {
        let mut node = index::IndexRoute::build_node();
        node.parent = Some("RootRoute".into());
        tree.add_route(node);
    }

    {
        let mut node = login::LoginRoute::build_node();
        node.parent = Some("RootRoute".into());
        tree.add_route(node);
    }

    {
        let mut node = blocking::BlockingRoute::build_node();
        node.parent = Some("RootRoute".into());
        tree.add_route(node);
    }

    {
        let mut node = awaited::AwaitedDemoRoute::build_node();
        node.parent = Some("RootRoute".into());
        tree.add_route(node);
    }

    {
        let mut node = lifecycle::LifecycleRoute::build_node();
        node.parent = Some("RootRoute".into());
        tree.add_route(node);
    }

    {
        let mut node = settings::SettingsRoute::build_node();
        node.parent = Some("RootRoute".into());
        tree.add_route(node);
    }

#[cfg(feature = "garde")]

    {
        let mut node = validation_test_garde::GardeTestRoute::build_node();
        node.parent = Some("RootRoute".into());
        tree.add_route(node);
    }

#[cfg(feature = "validify")]

    {
        let mut node = validation_test_validify::ValidifyTestRoute::build_node();
        node.parent = Some("RootRoute".into());
        tree.add_route(node);
    }

    {
        let mut node = validation_test_index::ValidationTestIndexRoute::build_node();
        node.parent = Some("RootRoute".into());
        tree.add_route(node);
    }

#[cfg(feature = "validator")]

    {
        let mut node = validation_test_validator::ValidatorTestRoute::build_node();
        node.parent = Some("RootRoute".into());
        tree.add_route(node);
    }

#[cfg(feature = "valico")]

    {
        let mut node = validation_test_valico::ValicoTestRoute::build_node();
        node.parent = Some("RootRoute".into());
        tree.add_route(node);
    }

    {
        let mut node = _auth_profile::ProfileRoute::build_node();
        node.parent = Some("AuthLayoutRoute".into());
        tree.add_route(node);
    }

    {
        let mut node = _auth::AuthLayoutRoute::build_node();
        node.parent = Some("AuthLayoutRoute".into());
        tree.add_route(node);
    }

    {
        let mut node = admin::AdminRoute::build_node();
        node.parent = Some("RootRoute".into());
        tree.add_route(node);
    }

    {
        let mut node = admin_dashboard::AdminDashboardRoute::build_node();
        node.parent = Some("RootRoute".into());
        tree.add_route(node);
    }

    {
        let mut node = docs_splat::DocsRoute::build_node();
        node.parent = Some("RootRoute".into());
        tree.add_route(node);
    }

    {
        let mut node = _marketing__about::MarketingAboutRoute::build_node();
        node.parent = Some("RootRoute".into());
        tree.add_route(node);
    }

    {
        let mut node = dashboard_index::DashboardIndexRoute::build_node();
        node.parent = Some("RootRoute".into());
        tree.add_route(node);
    }

    {
        let mut node = dashboard::DashboardRoute::build_node();
        node.parent = Some("RootRoute".into());
        tree.add_route(node);
    }

    {
        let mut node = dashboard_analytics::DashboardAnalyticsRoute::build_node();
        node.parent = Some("RootRoute".into());
        tree.add_route(node);
    }

    {
        let mut node = dashboard_settings::DashboardSettingsRoute::build_node();
        node.parent = Some("RootRoute".into());
        tree.add_route(node);
    }

    {
        let mut node = users_index::UsersIndexRoute::build_node();
        node.parent = Some("RootRoute".into());
        tree.add_route(node);
    }

    {
        let mut node = users____::OptionalUserRoute::build_node();
        node.parent = Some("RootRoute".into());
        tree.add_route(node);
    }

    {
        let mut node = users_param_id::UsersParamIdRoute::build_node();
        node.parent = Some("RootRoute".into());
        tree.add_route(node);
    }

    tree
}

/// Register all route components and loaders.
pub fn register_routes(cx: &mut gpui::App) {
about::AboutRoute::register(cx);
__root::RootRoute::register(cx);
scroll::ScrollRoute::register(cx);
index::IndexRoute::register(cx);
login::LoginRoute::register(cx);
blocking::BlockingRoute::register(cx);
awaited::AwaitedDemoRoute::register(cx);
lifecycle::LifecycleRoute::register(cx);
settings::SettingsRoute::register(cx);
#[cfg(feature = "garde")] validation_test_garde::GardeTestRoute::register(cx);
#[cfg(feature = "validify")] validation_test_validify::ValidifyTestRoute::register(cx);
validation_test_index::ValidationTestIndexRoute::register(cx);
#[cfg(feature = "validator")] validation_test_validator::ValidatorTestRoute::register(cx);
#[cfg(feature = "valico")] validation_test_valico::ValicoTestRoute::register(cx);
_auth_profile::ProfileRoute::register(cx);
_auth::AuthLayoutRoute::register(cx);
admin::AdminRoute::register(cx);
admin_dashboard::AdminDashboardRoute::register(cx);
docs_splat::DocsRoute::register(cx);
docs_splat::DocsRoute::register(cx);
_marketing__about::MarketingAboutRoute::register(cx);
dashboard_index::DashboardIndexRoute::register(cx);
dashboard::DashboardRoute::register(cx);
dashboard_analytics::DashboardAnalyticsRoute::register(cx);
dashboard_settings::DashboardSettingsRoute::register(cx);
users_index::UsersIndexRoute::register(cx);
users____::OptionalUserRoute::register(cx);
users_param_id::UsersParamIdRoute::register(cx);

}
