// AUTO-GENERATED by navi-codegen - DO NOT EDIT
use navi_router::RouteTree;

/// Build the route tree with all discovered routes.
pub fn build_route_tree() -> RouteTree {
    let mut tree = RouteTree::new();
    
    {
        let mut node = crate::routes::about::AboutRoute::build_node();
        node.parent = Some("RootRoute".into());
        tree.add_route(node);
    }

    {
        let mut node = crate::routes::__root::RootRoute::build_node();
        node.parent = None;
        tree.add_route(node);
    }

    {
        let mut node = crate::routes::index::IndexRoute::build_node();
        node.parent = Some("RootRoute".into());
        tree.add_route(node);
    }

    {
        let mut node = crate::routes::settings::SettingsRoute::build_node();
        node.parent = Some("RootRoute".into());
        tree.add_route(node);
    }

#[cfg(feature = "garde")]

    {
        let mut node = crate::routes::validation_test::garde::GardeTestRoute::build_node();
        node.parent = Some("RootRoute".into());
        tree.add_route(node);
    }

#[cfg(feature = "validify")]

    {
        let mut node = crate::routes::validation_test::validify::ValidifyTestRoute::build_node();
        node.parent = Some("RootRoute".into());
        tree.add_route(node);
    }

    {
        let mut node = crate::routes::validation_test::index::ValidationTestIndexRoute::build_node();
        node.parent = Some("RootRoute".into());
        tree.add_route(node);
    }

#[cfg(feature = "validator")]

    {
        let mut node = crate::routes::validation_test::validator::ValidatorTestRoute::build_node();
        node.parent = Some("RootRoute".into());
        tree.add_route(node);
    }

#[cfg(feature = "valico")]

    {
        let mut node = crate::routes::validation_test::valico::ValicoTestRoute::build_node();
        node.parent = Some("RootRoute".into());
        tree.add_route(node);
    }

    {
        let mut node = crate::routes::docs::param_::DocsRoute::build_node();
        node.parent = Some("RootRoute".into());
        tree.add_route(node);
    }

    {
        let mut node = crate::routes::users::param_id::UsersParamIdRoute::build_node();
        node.parent = Some("RootRoute".into());
        tree.add_route(node);
    }

    {
        let mut node = crate::routes::users::index::UsersIndexRoute::build_node();
        node.parent = Some("RootRoute".into());
        tree.add_route(node);
    }

    {
        let mut node = crate::routes::users::UsersRoute::build_node();
        node.parent = Some("RootRoute".into());
        tree.add_route(node);
    }

    tree
}
