// AUTO-GENERATED by navi-codegen - DO NOT EDIT

// Module declarations for discovered routes
#[path = "routes/__root.rs"] pub mod __root;
#[path = "routes/about.rs"] pub mod about;
#[path = "routes/docs/param_.rs"] pub mod docs_param_;
#[path = "routes/index.rs"] pub mod index;
#[path = "routes/settings.rs"] pub mod settings;
#[path = "routes/users/index.rs"] pub mod users_index;
#[path = "routes/users/mod.rs"] pub mod users;
#[path = "routes/users/param_id.rs"] pub mod users_param_id;
#[path = "routes/validation-test/garde.rs"] pub mod validation_test_garde;
#[path = "routes/validation-test/index.rs"] pub mod validation_test_index;
#[path = "routes/validation-test/valico.rs"] pub mod validation_test_valico;
#[path = "routes/validation-test/validator.rs"] pub mod validation_test_validator;
#[path = "routes/validation-test/validify.rs"] pub mod validation_test_validify;

/// Build the route tree with all discovered routes.
pub fn build_route_tree() -> navi_router::RouteTree {
    let mut tree = navi_router::RouteTree::new();

    {
        let mut node = about::AboutRoute::build_node();
        node.parent = Some("RootRoute".into());
        tree.add_route(node);
    }

    {
        let mut node = __root::RootRoute::build_node();
        node.parent = None;
        tree.add_route(node);
    }

    {
        let mut node = index::IndexRoute::build_node();
        node.parent = Some("RootRoute".into());
        tree.add_route(node);
    }

    {
        let mut node = settings::SettingsRoute::build_node();
        node.parent = Some("RootRoute".into());
        tree.add_route(node);
    }

#[cfg(feature = "garde")]

    {
        let mut node = validation_test_garde::ValidationTestGardeRoute::build_node();
        node.parent = Some("RootRoute".into());
        tree.add_route(node);
    }

#[cfg(feature = "validify")]

    {
        let mut node = validation_test_validify::ValidationTestValidifyRoute::build_node();
        node.parent = Some("RootRoute".into());
        tree.add_route(node);
    }

    {
        let mut node = validation_test_index::ValidationTestIndexRoute::build_node();
        node.parent = Some("RootRoute".into());
        tree.add_route(node);
    }

#[cfg(feature = "validator")]

    {
        let mut node = validation_test_validator::ValidationTestValidatorRoute::build_node();
        node.parent = Some("RootRoute".into());
        tree.add_route(node);
    }

#[cfg(feature = "valico")]

    {
        let mut node = validation_test_valico::ValidationTestValicoRoute::build_node();
        node.parent = Some("RootRoute".into());
        tree.add_route(node);
    }

    {
        let mut node = docs_param_::DocsParamRoute::build_node();
        node.parent = Some("RootRoute".into());
        tree.add_route(node);
    }

    {
        let mut node = users_param_id::UsersParamIdRoute::build_node();
        node.parent = Some("RootRoute".into());
        tree.add_route(node);
    }

    {
        let mut node = users_index::UsersIndexRoute::build_node();
        node.parent = Some("RootRoute".into());
        tree.add_route(node);
    }

    {
        let mut node = users::UsersUsersRoute::build_node();
        node.parent = Some("RootRoute".into());
        tree.add_route(node);
    }

    tree
}

/// Register all route components and loaders.
pub fn register_routes(cx: &mut gpui::App) {
about::AboutRoute::register(cx);
__root::RootRoute::register(cx);
index::IndexRoute::register(cx);
settings::SettingsRoute::register(cx);
#[cfg(feature = "garde")] validation_test_garde::ValidationTestGardeRoute::register(cx);
#[cfg(feature = "validify")] validation_test_validify::ValidationTestValidifyRoute::register(cx);
validation_test_index::ValidationTestIndexRoute::register(cx);
#[cfg(feature = "validator")] validation_test_validator::ValidationTestValidatorRoute::register(cx);
#[cfg(feature = "valico")] validation_test_valico::ValidationTestValicoRoute::register(cx);
docs_param_::DocsParamRoute::register(cx);
users_param_id::UsersParamIdRoute::register(cx);
users_index::UsersIndexRoute::register(cx);
users::UsersUsersRoute::register(cx);

}
