// AUTO-GENERATED by navi-codegen - DO NOT EDIT

// Module declarations for discovered routes


/// Build the route tree with all discovered routes.
pub fn build_route_tree() -> navi_router::RouteTree {
    let mut tree = navi_router::RouteTree::new();

    tree
}

/// Register all route components and loaders.
pub fn register_routes(cx: &mut gpui::App) {

}
